language: ruby
cache: bundler

sudo: false

branches:
  only:
    - master

before_install:
  - bundle --version
  - gem --version
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1

script:
  - bundle exec chefstyle
  - bundle exec rake spec
