language: ruby
cache: bundler

sudo: false

branches:
  only:
    - master

before_install:
  - bundle --version
  - gem --version
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0

script:
  - bundle exec chefstyle
  - bundle exec rake spec
