language: ruby
cache: bundler

sudo: false

branches:
  only:
    - master

before_install:
  - bundle --version
  - gem --version
rvm:
  - 2.2.5
  - 2.3.1

script:
  - bundle exec chefstyle
  - bundle exec rake spec
