# For more information about Expeditor, visit http://expeditor.es.chef.io
---
slack:
  notify_channel: releng-notify

github:
  version_tag_format: "v{{version}}"
  delete_branch_on_merge: true
  minor_bump_labels:
    - "Version: Bump Minor"

rubygems:
  - mixlib-cli

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Version: Skip Bump"
        - "Expeditor: Skip All"
  - bash:.expeditor/update_version.sh:
      only_if:
        - built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "Changelog: Skip Update"
        - "Expeditor: Skip All"
  - built_in:build_gem:
      only_if:
        - built_in:bump_version

promote:
  action:
    - built_in:publish_rubygems
    - built_in:rollover_changelog
